# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"
  config.vm.provision :shell, :path => "bootstrap.sh"
  
  # Provide a shared/synced folder with the swidGenerator source, to allow development on both machines
  config.vm.synced_folder "../../../swidGenerator", "/home/vagrant/swidGenerator"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Set up a host-only network
  config.vm.network :private_network, ip: "10.10.10.4"

  # Port forwarding
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 4343
  config.vm.network :forwarded_port, guest: 8000, host: 8000


end
